 CREATE TABLE `lineitem` (
  `L_ORDERKEY` bigint(20) NOT NULL,
  `L_PARTKEY` bigint(20) NOT NULL,
  `L_SUPPKEY` bigint(20) NOT NULL,
  `L_LINENUMBER` int(11) DEFAULT NULL,
  `L_QUANTITY` decimal(10,0) DEFAULT NULL,
  `L_EXTENDEDPRICE` decimal(10,0) DEFAULT NULL,
  `L_DISCOUNT` decimal(10,0) DEFAULT NULL,
  `L_TAX` decimal(10,0) DEFAULT NULL,
  `L_RETURNFLAG` char(1) DEFAULT NULL,
  `L_LINESTATUS` char(1) DEFAULT NULL,
  `L_SHIPDATE` date DEFAULT NULL,
  `L_COMMITDATE` date DEFAULT NULL,
  `L_RECEIPTDATE` date DEFAULT NULL,
  `L_SHIPINSTRUCT` char(25) DEFAULT NULL,
  `L_SHIPMODE` char(10) DEFAULT NULL,
  `L_COMMENT` varchar(44) DEFAULT NULL
)
PARTITION BY RANGE COLUMNS(L_SHIPDATE) (
  PARTITION p1 VALUES LESS THAN ('1993-01-01'),
  PARTITION p2 VALUES LESS THAN ('1994-01-01'),
  PARTITION p3 VALUES LESS THAN ('1995-01-01'),
  PARTITION p4 VALUES LESS THAN ('1996-01-01'),
  PARTITION p5 VALUES LESS THAN ('1997-01-01'),
  PARTITION p6 VALUES LESS THAN ('1998-01-01'),
  PARTITION p7 VALUES LESS THAN ('1999-01-01'),
  PARTITION p8 VALUES LESS THAN (MAXVALUE)  
);